//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string phone { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> company { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> contact_group { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public byte[] photo { get; set; }
    
        public virtual company company1 { get; set; }
        public virtual contact_group contact_group1 { get; set; }
        public virtual position position1 { get; set; }
    }
}
