//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneDirectory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhoneDirectoryEntities : DbContext
    {
        public PhoneDirectoryEntities()
            : base("name=PhoneDirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<contact_group> contact_group { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
